apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-worker
  namespace: budget
spec:
  selector:
    matchLabels:
      app: backend-worker
  template:
    metadata:
      labels:
        app: backend-worker
    spec:
      volumes:
        - name: secret-store
          csi:
            driver: 'secrets-store.csi.k8s.io'
            readOnly: true
            volumeAttributes:
              secretProviderClass: 'worker-vault'
        - name: appsettings-template
          configMap:
            name: worker-config-map
        - name: appsettings-final
          emptyDir: {}
      initContainers:
        - name: appsettings-prep
          image: busybox
          command:
            - sh
            - -c
            - |
              cp /template/appsettings.Production.json /app/appsettings.Production.json
              sed -i "s/{{dbConnectionString}}/$(cat /mnt/secrets-store/dbConnectionString)/" /app/appsettings.Production.json
              sed -i "s/{{natsConnectionString}}/nats:\/\/$(cat /mnt/secrets-store/natsUsername):$(cat /mnt/secrets-store/natsPassword)@nats:4222/" /app/appsettings.Production.json
          volumeMounts:
            - name: secret-store
              mountPath: /mnt/secrets-store
              readonly: true
            - name: appsettings-template
              mountPath: /template
              readOnly: true
            - name: appsettings-final
              mountPath: /app
      containers:
        - name: backend-worker-container
          image: registry.timo-hermans.nl/budget-worker:2025.10.10.7
          envFrom:
            - secretRef:
                name: worker-secret
            - configMapRef:
                name: worker-config-map
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: appsettings-final
              mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
      imagePullSecrets:
        - name: regcred
